// Mocks generated by Mockito 5.4.4 from annotations
// in shoesly_priority_soft/test/features/brand/presentation/bloc/brand_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shoesly_priority_soft/core/model/base_response.dart' as _i2;
import 'package:shoesly_priority_soft/features/brand/data/models/brand_model.dart'
    as _i5;
import 'package:shoesly_priority_soft/features/brand/domain/usecases/get_brand_list.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetBrandList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBrandList extends _i1.Mock implements _i3.GetBrandList {
  @override
  _i4.Future<_i2.BaseResponse<List<_i5.BrandModel>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i5.BrandModel>>>.value(
            _FakeBaseResponse_0<List<_i5.BrandModel>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i5.BrandModel>>>.value(
                _FakeBaseResponse_0<List<_i5.BrandModel>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i5.BrandModel>>>);
}
